#!/usr/bin/env bash

cd $HOME/personal/
git clone https://github.com/neovim/neovim
cd neovim

make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install

rm -rf $HOME/.config/nvim

mkdir -p $HOME/.config/nvim

ln -s $HOME/personal/dotfiles/.config/nvim $HOME/.config/nvim
